// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX0LoxI6Nn1sKSbWZZTTZcP_P1P9VFU9U',
    appId: '1:305595097231:web:40f3e880762748f0b910fa',
    messagingSenderId: '305595097231',
    projectId: 'whatsapp-c2353',
    authDomain: 'whatsapp-c2353.firebaseapp.com',
    storageBucket: 'whatsapp-c2353.appspot.com',
    measurementId: 'G-YMHVJCQ9P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqMjilDE5z0vDCHtyEY652yql5OIXd7Y',
    appId: '1:305595097231:android:9938c1056a7e4957b910fa',
    messagingSenderId: '305595097231',
    projectId: 'whatsapp-c2353',
    storageBucket: 'whatsapp-c2353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhCNh7lvMFeGg1xzsWLN-ueYRYbA56z_o',
    appId: '1:305595097231:ios:e911c26c2a73f60ab910fa',
    messagingSenderId: '305595097231',
    projectId: 'whatsapp-c2353',
    storageBucket: 'whatsapp-c2353.appspot.com',
    iosClientId: '305595097231-9kc58e3a9d9a21jkfn18rgem3d64crl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhCNh7lvMFeGg1xzsWLN-ueYRYbA56z_o',
    appId: '1:305595097231:ios:e1bc27c270fcb8a9b910fa',
    messagingSenderId: '305595097231',
    projectId: 'whatsapp-c2353',
    storageBucket: 'whatsapp-c2353.appspot.com',
    iosClientId: '305595097231-rh3qe7igo2l4sn2dgb04f6c02tm27qni.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp.RunnerTests',
  );
}
